org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=true

# LiteRT-LM 0.17.1 is compiled with Kotlin 2.4 metadata.
# AGP 9.4 built-in Kotlin is 2.2.10, so temporarily use external KGP 2.4.10.
android.builtInKotlin=false
android.newDsl=false
